### ISSUE TITLE
Dongle not working after Update

### ISSUE THREAD

**Issue by mobergmann** [szszoke/sennheiser-gsp670-pulseaudio-profile#10] opened 2021-02-25 17:41 UTC
I updated the EPOS Driver, the Dongle Driver, and the Headset Driver via EPOS (on a windows machine). After the update, I'm not able to use the Headset without the cable anymore, in other words, I cannot use the Dongle anymore.

**Comment by szszoke** [comment] 2021-02-25 17:43
This is already discussed over #5 but maybe we should have a dedicated issue.

Something changed that caused the ALSA drivers to not work currently. This is not an issue that is related to this profile itself. It goes deeper.

**Comment by techy2493** [comment] 2021-03-22 03:57
I'm going to start looking into this as well as I just got a GSP670 to work on Manjaro but of course the first thing I did was use it on my windows VM and update all the firmware without looking into compatibility like an idiot...

Just for reference, I found another thread szszoke made discussing this issue and for my sanity I'm going to mention it here so I and anyone else can refer to it later.
https://forum.manjaro.org/t/sennheiser-gsa-70-arecord-lists-usb-sound-card-but-cannot-record-audio-open-error-no-such-file-or-directory/53511/8

Has anyone else heard any updates on this? 

@szszoke  is the branch you refer to in this post still suitable to use to attempt to use the new firmware?

**Comment by szszoke** [comment] 2021-03-23 08:20
Sorry for the late reply!

Unless an update changed how the mixer profiles are configured, the branch should still partially work for the new firmware.

**Comment by WillyChuck** [comment] 2021-03-23 11:44
FTR I spent some hours trying to get this to work. I recorded the verbose
output of 'lsusb' for the headset connected via USB cable and via the USB
dongle. There are remarkably few differences:

   - There are two audio devices presented -- 'main' and 'communications'.
   - The order that they're presented to the computer has been reversed in
   the latest dongle firmware.
   - The unit numbers of each sub-device (input or output) has changed in
   the latest dongle firmware.
   - The USB manufacturer and device ID has changed in the latest dongle
   firmware.

There are no other detected changes; not that proves anything at all. There
could of course be undetected issues. But I suspect that we're simply not
enumerating the device IDs correctly to identify what's an input, or
output, and of what type.

**Comment by szszoke** [comment] 2021-03-23 11:50
You are correct. There are more discussions regarding your discoveries in #5.

The problem is that even when attempting to use the device directly via ALSA, errors are reported.

**Comment by WillyChuck** [comment] 2021-03-23 12:18
So, the suspicion is that a lower-level change has occurred; it's not a PulseAudio issue but lower down the stack? We have a new hardware device with no low-level driver support? That's surprising. Or we're misidentifying the low-level device now? I wonder whether there's a Nintendo Switch headset specification out there?

**Comment by szszoke** [comment] 2021-03-23 12:31
This is just a guess, but what I think happened was that in order to support the Nintendo Switch, the dongle had to implement some kind of non-standard USB audio device.

In order to not cause issues with drivers, the USB device ID was changed.

There are Windows drivers for the new dongle.
There is usually no driver required for Mac OS when a device is fully USB class compliant, but there is no Mac OS support advertised for the dongle so that again tells me that the new dongle is not USB class compliant.

The new dongle would either need a custom driver or a quirk to work around the alterations in the USB protocol.

**Comment by techy2493** [comment] 2021-03-23 15:21
I've also raised a ticket with EPOS (Sennheiser) support it's made it into their zendesk system I will update if they provide any feedback on the change or if they will provide any support for us or details on what changed so that we can get the right fix implemented.

**Comment by techy2493** [comment] 2021-03-26 18:03
EPOS just confirmed they will have a fix for this in the next firmware update release.

They did not tell me when that would be.

**Comment by szszoke** [comment] 2021-03-26 18:07
That sounds promising. Now we wait.

Thanks!

**Comment by techy2493** [comment] 2021-03-27 09:53
I pushed a little and got a response with a date.

"On the month of May, we will release a new firmware version."

So we have a bit of a wait, but at least they intend to fix it, and reasonably soon.

**Comment by ArcadesSaboth** [comment] 2021-04-01 18:36
Hello,
First of all thank you immensely for this repo @szszoke.
@techy2493 so... did they explicitly tell you they are going to fix this for linux?

**Comment by techy2493** [comment] 2021-04-04 07:54
Here is the exact working of the original request I put in, followed by their response.
**EPOS Support Request**
```
The most recent firmware does not seem to work on linux anymore.

See https://github.com/szszoke/sennheiser-gsp670-pulseaudio-profile/issues/10

A thread which discusses this issue in a publicly released PulseAudio profile. There is additional discussion on the Manjaro forums linked.

Are there any plans to fix this issue?

```

**EPOS Response**
```
Thank you for your patience.

Yes, the issue will be fixed when we will release a new firmware version.

Do not hesitate to contact us if you have any question.


We wish you a nice day!
```

This seems to be to be direct confirmation that they are going to fix this issue for linux.

**Comment by ArcadesSaboth** [comment] 2021-04-04 18:19
@techy2493 ah that's amazing! Thank you.
It's very nice to hear that companies care about Linux, albeit in a semi-official way. I can understand they won't provide official support for the platform but they do fixes if they can.

**Comment by koiakoia** [comment] 2021-05-03 15:30
Alternate Branch allows headest to provide sound on Ubuntu 21.04 although it was fine with output without profiles.  However I still am not getting an input with this.  Device shows up in arecord -l but does not seem to get shown to os via pulse.

**Comment by matth2k** [comment] 2021-06-08 18:08
```
Pravesh Singh (EPOS Gaming)

Jun 8, 2021, 17:48 UTC

Dear Matt,

Referring to your support ticket number 153123. Please accept my sincere apologies for the delayed response. Unfortunately, the GSP 670 is not officially supported on Linux and we do not have any plans as of now for compatibility on Linux. We have passed on your feedback to our developer team.

Please let us know if you need any further information. Thank you and we wish you a nice day!

Best regards,
Pravesh Singh
EPOS Global Support
```
:(

**Comment by mobergmann** [comment] 2021-06-08 18:12
Can we get a way to downgrade the firmware of the headset to the working version?

**Comment by WillyChuck** [comment] 2021-06-08 22:09
I've just resorted to a USB cable when using my work Linux box, using the
dongle for Windows use only. Bluetooth works, but my colleagues tell me
that sound quality is awful in video conferencing.

**Comment by juanmreyesa** [comment] 2021-07-16 18:56
Sadly the're no way to download the firmware...


```
This is with regards to your support ticket number 161641. Unfortunately, there's no option to downgrade the firmware for the headset or the dongle. Once, the headset or the dongle is updated, it deletes the previous firmware.

Please let us know if you need any further information or shall we close this ticket in our system? 

We thank you and we wish you a nice day!
```

**Comment by vk496** [comment] 2021-09-03 09:09
Hi,

Just the same problem here with my GSP 670. I've tried the branch https://github.com/szszoke/sennheiser-gsp670-pulseaudio-profile/tree/new-dongle-firmware

Using that branch, I have a output profile "EPOS GSA 70 Stereo analogic" which output the main volume. No Communication neither Input profile.

The interesting stuff is when I switch to the "Pro audio" config. Then I have 2 output profiles (Pro and Pro1) which make works the Main and Communication profile, but still no mic

Related with #14 #15

**Comment by szszoke** [comment] 2021-09-03 10:09
@vk496 you need to patch the USB audio driver in your kernel. You can find more in #13.

Edit: look at the comment made by @bundabrg - https://github.com/szszoke/sennheiser-gsp670-pulseaudio-profile/issues/13#issuecomment-891662521

**Comment by szszoke** [comment] 2021-11-22 11:13
If you are running PipeWire, try to remove the profile entirely. It doesn't seem to be needed anymore. See #18

**Closed as completed by szszoke** 2021-11-22 11:13 UTC
